import mongoose, { Schema } from "mongoose";

export const sheetSchema = new Schema({
  player_id: String,
  character: {
    character_name: { type: String, default: "" },
    character_class: { type: String, default: "" },
    level: { type: Number, default: 0 },
    race: { type: String, default: "" },
    background: { type: String, default: "" },
    alignment: { type: String, default: "" },
    xp: { type: Number, default: 0 },
    personality_trait: { type: String, default: "" },
    ideals: { type: String, default: "" },
    bonds: { type: String, default: "" },
    flaws: { type: String, default: "" },
    features_and_traits: { type: String, default: "" },
  },
  abilities: {
    strength: { type: Number, default: 0 },
    dexterity: { type: Number, default: 0 },
    constitution: { type: Number, default: 0 },
    intelligence: { type: Number, default: 0 },
    wisdom: { type: Number, default: 0 },
    charisma: { type: Number, default: 0 },
  },
  passive_wisdom: { type: Number, default: 0 },
  inspiration: { type: Number, default: 0 },
  proficiency_bonus: { type: Number, default: 0 },
  saving_throws: {
    saving_strength: { type: Boolean, default: false },
    saving_dexterity: { type: Boolean, default: false },
    saving_constitution: { type: Boolean, default: false },
    saving_intelligence: { type: Boolean, default: false },
    saving_wisdom: { type: Boolean, default: false },
    saving_charisma: { type: Boolean, default: false },
  },
  skills: {
    acrobatics: { type: Boolean, default: false },
    animal_handling: { type: Boolean, default: false },
    arcana: { type: Boolean, default: false },
    athletics: { type: Boolean, default: false },
    deception: { type: Boolean, default: false },
    history: { type: Boolean, default: false },
    insight: { type: Boolean, default: false },
    intimidation: { type: Boolean, default: false },
    investigation: { type: Boolean, default: false },
    medicine: { type: Boolean, default: false },
    nature: { type: Boolean, default: false },
    perception: { type: Boolean, default: false },
    performance: { type: Boolean, default: false },
    persuasion: { type: Boolean, default: false },
    religion: { type: Boolean, default: false },
    sleight_of_hand: { type: Boolean, default: false },
    stealth: { type: Boolean, default: false },
    survival: { type: Boolean, default: false },
  },
  other_proficiencies: { type: [String], default: [] },
  combat: {
    armor_class: { type: Number, default: 0 },
    initiative: { type: Number, default: 0 },
    speed: { type: Number, default: 0 },
    hp: {
      max_hp: { type: Number, default: 0 },
      current_hp: { type: Number, default: 0 },
      temporary_hp: { type: Number, default: 0 },
      hp_dice: { type: String, default: "" },
    },
    death_saves: {
      successes: { type: Number, default: 0 },
      failures: { type: Number, default: 0 },
    },
    attacks_and_spells: [
      {
        attack_name: { type: String, default: "" },
        attack_bonus: { type: Number, default: 0 },
        damage: { type: Number, default: 0 },
        damage_type: { type: String, default: "" },
      },
    ],
  },
  bag: {
    money: {
      cp: { type: Number, default: 0 },
      sp: { type: Number, default: 0 },
      ep: { type: Number, default: 0 },
      gp: { type: Number, default: 0 },
      pp: { type: Number, default: 0 },
    },
    equipment: { type: [String], default: [] },
  },
});

export const Sheet = mongoose.model("Sheet", sheetSchema);
